20100 MainProcess 2023-07-26 15:56:31,730
Traceback (most recent call last):
  File "D:\Project\lunar\env\lib\site-packages\pyarmor\cli\__main__.py", line 698, in main
    main_entry(sys.argv[1:])
  File "D:\Project\lunar\env\lib\site-packages\pyarmor\cli\__main__.py", line 686, in main_entry
    args.func(ctx, args)
  File "D:\Project\lunar\env\lib\site-packages\pyarmor\cli\__main__.py", line 225, in cmd_gen
    builder.process(options)
  File "D:\Project\lunar\env\lib\site-packages\pyarmor\cli\generate.py", line 152, in process
    self.generate_runtime_package(self.ctx.outputs[0])
  File "D:\Project\lunar\env\lib\site-packages\pyarmor\cli\generate.py", line 93, in generate_runtime_package
    Pytransform3.generate_runtime_package(self.ctx, output)
  File "D:\Project\lunar\env\lib\site-packages\pyarmor\cli\core\__init__.py", line 108, in generate_runtime_package
    return m.generate_runtime_package(ctx, output, platforms)
  File "<maker>", line 877, in generate_runtime_package
  File "<maker>", line 488, in build
  File "<maker>", line 367, in patch_extension
PermissionError: [Errno 13] Permission denied: 'dist\\pyarmor_runtime_000000\\pyarmor_runtime.pyd'
